In [2]:
import tensorflow as tf

C:\Users\Arya\anaconda3\Lib\site-packages\h5py\__init__.py:36: UserWarning: h5py is running against HDF5 1.14.6 when it was built against 1.14.5, this may cause problems
  _warn(("h5py is running against HDF5 {0} when it was built against {1}, "


In [2]:
daily_sales_number=[21,22,-108,31,-1,32,34,31]

In [3]:
tf_dataset=tf.data.Dataset.from_tensor_slices(daily_sales_number)
tf_dataset

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [4]:
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

21
22
-108
31
-1
32
34
31


In [5]:
#print 1st 3 elements
for sales in tf_dataset.take(3):
    print(sales.numpy())

21
22
-108


In [8]:
#filter out negative numbers
tf_2dataset=tf_dataset.filter(lambda x:x>0)
for sales in tf_2dataset.as_numpy_iterator():
    print(sales)

21
22
31
32
34
31


In [9]:
#multiply all elements with 72
tf_dataset=tf_2dataset.map(lambda x:x*72)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

1512
1584
2232
2304
2448
2232


In [10]:
#pass values as batch
for sales_batch in tf_dataset.batch(2):
    print(sales_batch.numpy())

[1512 1584]
[2232 2304]
[2448 2232]


In [13]:
#doing all operations as a single command line
tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales_number)
tf_dataset=tf_dataset.filter(lambda x:x>0).map(lambda y:y*72).shuffle(2).batch(2)
for sales in tf_dataset.as_numpy_iterator():
    print(sales)

[1512 2232]
[1584 2448]
[2232 2304]


CATS AND DOGS 

In [11]:
image_ds=tf.data.Dataset.list_files(r"C:\c&d\PetImages\*\*",shuffle=False)
for file in image_ds.take(3):
    print(file.numpy())

b'C:\\c&d\\PetImages\\Cat\\0.jpg'
b'C:\\c&d\\PetImages\\Cat\\1.jpg'
b'C:\\c&d\\PetImages\\Cat\\10.jpg'


In [9]:
class_name=['cat','dog']

In [13]:
image_count=len(image_ds)
image_count

24998

In [14]:
train_size=int(image_count*0.8)

train_ds=image_ds.take(train_size)
test_ds=image_ds.skip(train_size)

In [15]:
len(train_ds)

19998

In [16]:
len(test_ds)

5000

In [21]:
def get_label(file_path):
    parts=tf.strings.split(file_path,'\\')
    return parts[-2]
                           

In [30]:
def process_image(file_path):
    labels=get_label(file_path)

    img=tf.io.read_file(file_path)
    img=tf.image.decode_jpeg(img)
    img=tf.image.resize(img,[128,128])

    return img,labels
    

In [32]:
train_ds=train_ds.map(process_image)
for img,labels in train_ds.take(3):
    print(img)
    print(labels)

tf.Tensor(
[[[202.45312   165.45312    87.453125 ]
  [206.35938   169.35938    91.359375 ]
  [209.26562   172.26562    94.265625 ]
  ...
  [244.73438   207.        124.53125  ]
  [242.        204.        119.71875  ]
  [238.45312   201.45312   120.453125 ]]

 [[202.45312   165.45312    87.453125 ]
  [206.35938   169.35938    91.359375 ]
  [209.26562   172.26562    94.265625 ]
  ...
  [244.76239   208.31506   126.84509  ]
  [243.        205.64294   122.32147  ]
  [239.40533   202.40533   121.405334 ]]

 [[202.45312   165.45312    87.453125 ]
  [206.35938   169.35938    91.359375 ]
  [209.26562   172.26562    94.265625 ]
  ...
  [245.        210.        128.87091  ]
  [243.        206.        125.       ]
  [240.45312   203.45312   122.453125 ]]

 ...

 [[157.47266   125.         54.17578  ]
  [158.47266   126.         55.17578  ]
  [159.64844   127.17578    56.351562 ]
  ...
  [  3.          4.          0.       ]
  [  3.          4.          0.       ]
  [  2.1757812   3.1757812   0.  

In [33]:
def scale(img,labels):
    return img/255,labels

In [34]:
train_ds=train_ds.map(scale)
for img,labels in train_ds.take(4):
    print(img.numpy()[0][0])
    print(labels)

[0.7939338  0.6488358  0.34295344]
tf.Tensor(b'Cat', shape=(), dtype=string)
[0.1419424  0.16939338 0.1419424 ]
tf.Tensor(b'Cat', shape=(), dtype=string)
[0.11322476 0.13638653 0.15991594]
tf.Tensor(b'Cat', shape=(), dtype=string)
[0.87058824 0.8745098  0.8509804 ]
tf.Tensor(b'Cat', shape=(), dtype=string)
